vertices:
  - name: in
    next: [cat]
    source:
      generator: {}
  - name: in2
    next: [cat]
    source:
      generator: {}
  - name: cat
    udf:
      dlq: true
      container:
        image: quay.io/numaio/numaflow-go/map-cat:stable 
        imagePullPolicy: Always
  - name: cat2
    udf:
      container:
        image: quay.io/numaio/numaflow-go/map-cat:stable 
        imagePullPolicy: Always
  - name: out
    sink:
      log: {}
