apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: {{ .Release.Name }}
spec:
  vertices: 
{{- range .Values.vertices }}
    - name: {{ .name }}
      scale:
        min: 1

{{- if .preset }}
{{- $presetName := .preset }}
{{- range $.Values.presets }}
{{- if eq .name $presetName }}
{{- $withoutName := omit . "name" }}
{{ toYaml $withoutName | indent 6 }}
{{- end }}
{{- end }}
{{- end }}


{{- if .source }}
      source: 
{{ toYaml .source | indent 8 }}
{{- end }}

{{- if .udf }}
      udf:
{{ toYaml .udf | indent 8 }}
{{- if .udf.dlq }}
    - name: {{ .name }}-dlq
      scale:
        min: 1
      sink:
        log: {}
{{- end }}
{{- end }}

{{- if .sink }}
      sink:
{{ toYaml .sink | indent 8 }}     
{{- end }}

{{- end }}


  edges:
{{- $vertices := .Values.vertices }}
{{- range $i, $v := $vertices }}

{{- if .next }}

{{- range .next }}
    - from: {{ $v.name }}
      to: {{ .name }}
{{- if .conditions}}
      conditions:
{{ toYaml .conditions | indent 8 }}
{{- end }}
{{- end }}

{{- else if and (not $v.sink) (lt (add $i 1) (len $vertices)) }}
    - from: {{ $v.name }}
      to: {{ (index $vertices (add $i 1)).name }}
{{- end }}

{{- if and $v.udf $v.udf.dlq }}
    - from: {{ $v.name }}
      to: {{ $v.name }}-dlq
{{- end }}

{{- end }}