apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: {{ .Release.Name }}
spec:
  vertices: 
{{ toYaml .Values.vertices | indent 4 }}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out